### ISSUE TITLE
Suggestion list with selected remains after select (mobile)

### ISSUE THREAD

**Issue by cyk** [ubilabs/react-geosuggest#208] opened 2016-09-23 23:42 UTC
### Short description

Using a mobile device, upon tapping a suggestion, all suggestions in the list clear except for selected.
### Expected results

I expected that the suggestion list would clear entirely after selecting a suggestion (i.e., how it behaves on the desktop).
### Actual results

The suggestion list continues to show the selected suggestion until it is selected again.
### Reproduction steps
1. Go to http://ubilabs.github.io/react-geosuggest/ (Android Chrome 53)
2. Tap into 'Search Places' input
3. Type the name of a place
4. Tap first suggestion
5. Suggestion list is reduced to selected suggestion
### Additional Information

<img src="https://cloud.githubusercontent.com/assets/423755/18804183/75ce1aea-81ac-11e6-94f0-032a96ab1fbc.gif" width="300" />

**Comment by Scarysize** [comment] 2016-09-30 13:55
Can't reproduce this on my device (Moto G, Chrome 53).
What device are you using?

**Comment by cyk** [comment] 2016-09-30 19:14
We've reproduce it on a Samsung Galaxy S5 and Moto X Pure Edition (2014).

**Comment by ro-ka** [comment] 2016-12-14 14:41
Cannot reproduce neither (Moto X Play 2015).

**Comment by cyk** [comment] 2016-12-17 17:32
Can no longer reproduce on Moto X Pure Edition (2014) with Chrome 55.

**Comment by ro-ka** [comment] 2016-12-19 10:25
Will close it then. Thanks for reporting though!

**Closed by ro-ka** 2016-12-19 10:25 UTC
Labels: bug, feedback needed, help wanted
