### ISSUE TITLE
Show suggestions on resultset > 0 instead of focus

### ISSUE THREAD

**Issue by jwamsterdam** [ubilabs/react-geosuggest#141] opened 2016-05-31 20:37 UTC
Hi, 

I have my suggestions styled by css with a border of 1px. What happens is that the resultset is hidden by max-height 0px, but this doesn't hide the complete div, since the border remains visible with a horizontal line of 2 px (top and bottom of the div).

Could the code be changed that the suggestions only become visible when the google resultset is bigger than 1 result (instead of focus on the input field)?

I think this is a way nicer solution and fixes the problem of the border not completely being hidden with max-height 0px.

Thank you!

**Comment by ro-ka** [comment] 2016-06-02 14:32
We will hide the suggestion list when there are no results from either the Google Maps API or the fixtures.

**Comment by Caerostris** [comment] 2016-06-03 14:36
@jwamsterdam I am unable to reproduce the exact same bug you described. Could you check if #153 fixes your issue?

**Comment by jwamsterdam** [comment] 2016-06-03 18:34
You can reproduce is you use the following css:

    .geosuggest__suggests{
        padding: 5px 0;
        margin: 2px 0 0;*/
        position: absolute;
        margin-top: 38px;
        z-index: 999;
        width: 100%;
        font-size: 14px;
        text-align: left;
        list-style: none;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid rgba(0,0,0,.15);
        border-radius: 4px;
        box-shadow: 0 6px 12px rgba(0,0,0,.175);
    }
    .geosuggest__suggests li {
        margin: 10px 0px 10px -40px;
        display: block;
        padding: 3px 20px;
        clear: both;
        font-weight: 400;
        line-height: 1.42857143;
        color: #333;
    }

**Comment by Caerostris** [comment] 2016-06-17 07:09
#153 has been merged into master. This PR implements the fixes you proposed.
Could you please verify that it fixes your issue?

**Comment by Caerostris** [comment] 2016-06-22 07:09
Now also on npm.

**Comment by ro-ka** [comment] 2016-07-29 12:41
Please reopen when the issue still occurs.

**Closed by ro-ka** 2016-07-29 12:41 UTC
Labels: enhancement
