### ISSUE TITLE
React missing key property on SuggestItem ?

### ISSUE THREAD

**Issue by vorthess** [ubilabs/react-geosuggest#328] opened 2017-06-21 11:10 UTC
### Short description

I placed input 
```
<div className="suggest-input">
                <Geosuggest
                    onSuggestSelect={this.onSelect.bind(this)}
                    googleMaps={this.props.maps}/>
            </div>
```

### Expected results

I expect it to work properly and it works

### Actual results

After showing list with results, I get:

```
proxyConsole.js:56 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `SuggestItem`. See https://fb.me/react-warning-keys for more information.
    in b (created by SuggestItem)
    in SuggestItem (created by SuggestList)
    in ul (created by SuggestList)
    in SuggestList (created by Geosuggest)
    in div (created by Geosuggest)
    in div (created by Geosuggest)
    in Geosuggest (at SuggestInput.js:30)
    in div (at SuggestInput.js:29)
```

### Reproduction steps

Just put component there

### Additional Information

It doesnt affect it's behavior and works properly, however I got the error. Also I see key={} is provided, so I don't know why it's there?

**Comment by ro-ka** [comment] 2017-06-21 13:00
Duplicate of #326.

**Closed by ro-ka** 2017-06-21 13:00 UTC
