### ISSUE TITLE
Remove fixtures when input has value

### ISSUE THREAD

**Issue by Alin13** [ubilabs/react-geosuggest#457] opened 2020-04-11 23:57 UTC
### Short description

I'm trying to remove the fixtures when the input has value.

### Expected results

The fixtures should be removed

### Actual results

The fixtures are still there

### Additional Information
I saved the input value into the state using onChange method, and I tried the following methods:
```
const [value, setValue] = useState('');
```

1. Using the fixtures prop and the state to filter the fixtures.

```
<Geosuggest
        fixtures={fixtures.filter(({ label }) => label.loLowerCase().includes(value))}
        onChange={(v) => {
             setValue(v.toLowerCase());
         }}
```
or

```
<Geosuggest
        fixtures={value ? null : fixtures)}
        onChange={(v) => {
             setValue(v.toLowerCase());
         }}
```

2. Using the skipSuggest prop (as suggested here: https://github.com/ubilabs/react-geosuggest/issues/371)
Note: there is no isFixtures property on the skipSuggest parameter, but only the fixtures have label

```
<Geosuggest
        skipSuggest={({ label }) => !!(value && label)}
        fixtures={fixtures}
        onChange={(v) => {
             setValue(v.toLowerCase());
         }}
```

I even tried changing maxFixtures base on the value, but it didn't work.

Is there any solution to this problem ? Or is there something wrong in my code ?
Thank you for your time!

**Comment by waltermvp** [comment] 2020-04-27 03:47
Im running into the same issue, any updates on this @Alin13

**Comment by Alin13** [comment] 2020-04-27 19:16
Nothing yet. And it seems no one will ever read those issues, 👎

**Comment by jalanga** [comment] 2020-04-28 20:47
+1

**Comment by waltermvp** [comment] 2020-04-28 21:17
@Alin13 @jalanga fork and fix? who is down?

**Comment by annikabock** [comment] 2020-04-29 07:41
Will be fixed by Ubilabs upcoming week

**Comment by ro-ka** [comment] 2020-05-07 09:43
I try to reproduce this. For me it works as expected when I use your second suggestion. But instead of `null` I pass in `undefined` because TypeScript.  😃

So this is the minimal example that works:
```js
/* global google */

import React, {useState} from 'react';
import ReactDOM from 'react-dom';
import Geosuggest from 'react-geosuggest';

const App = () => {
  const [suggestValue, setSuggestValue] = useState('');

  /**
   * When the input got changed
   */
  const onChange = (value) => {
    setSuggestValue(value);
    console.log(`input changes to : ${value}`);
  };

  const fixtures = [
    {label: 'New York', location: {lat: 40.7033127, lng: -73.979681}},
    {label: 'Rio', location: {lat: -22.066452, lng: -42.9232368}},
    {label: 'Tokyo', location: {lat: 35.673343, lng: 139.710388}}
  ];

  return (
    <Geosuggest
      fixtures={suggestValue ? undefined : fixtures}
      onChange={onChange}
      location={new google.maps.LatLng(53.558572, 9.9278215)}
      radius="20"
    />
  );
};

ReactDOM.render(<App />, document.getElementById('app'));
```

Can you provide a complete not-working example? Would love to figure this out!

**Comment by Alin13** [comment] 2020-05-07 16:47
Hey,

Thank you for your response. Your example works just fine.

I think the problem is when you also use the **minLength** prop. If **suggestValue**'s length is smaller than the **minLength**, the change handler is called, but the fixtures are not rerendered. They are rerendered only when the text length is greater than or equal to the minLength value.

I don't know if this is a bug or the expected behavior. Thanks!

**Comment by ro-ka** [comment] 2020-05-08 06:15
Ah, thanks! Could reproduce it and fixed it. When the PR went through I’ll publish later today.

**Closed** 2020-05-08 12:21 UTC
Labels: bug
