### ISSUE TITLE
Suggestion list hidden class not updating properly

### ISSUE THREAD

**Issue by Shooshte** [ubilabs/react-geosuggest#327] opened 2017-06-21 10:51 UTC
When I select a suggestion from the list, and then clear the input with ctr+a *without triggering `.onBlur()`, and start typing a different input string the suggestion list class does not update it's class from `.geosuggest__suggests--hidden`, and suggestions do not get populated properly (there is no network call). Rolling back to version 1.25.0 removes the issues (this is the version that I am using in another project, but I am not sure that this is the last version that has the functionality working).

I tried adding a `.onFocus()` call to the onChange event, thinking this will solve my issue, but nothing happens.

My implementation:
```
import React, {PropTypes} from 'react'
import Geosuggest from 'react-geosuggest'
import onClickOutside from 'react-onclickoutside'
import {observer, inject} from 'mobx-react'
import s from 'styled-components'
import {Icon} from 'semantic-ui-react'

@inject('uiStore')
@observer
class LocationSearch extends React.Component {

  setMapLocation = data => {
    this.props.uiStore.lat = data.location.lat
    this.props.uiStore.lng = data.location.lng
  };

  onChange = () => {
    this.geoSuggest.focus()
  }

  render() {
    return (
      <LocationSearchStyle>
        <div
          id="searchBox">
          <Icon name='search' color='olive' className='searchBox-icon'/>
          <Geosuggest ref={el=>this.geoSuggest=el} onSuggestSelect={this.setMapLocation} onChange={this.onChange} className="geoLocation"/>
        </div>
      </LocationSearchStyle>
    );
  }
}

const LocationSearchStyle = s.div `
  #searchBox {
    position: absolute;
    right: 129px;
    top: .5em;
    display: flex;
    align-items: center;
    background-color: #3f3f3f;
    justify-items: center;
    padding-left: 1em;
  }
  .geoLocation {
    display: inline-flex;

  }
  .geoLocation input {
    border: none;
    color: #fff;
    background-color: #3f3f3f;
    padding: 16px 8px;
    color: #fff;
  }
  .geoLocation input:focus {
    outline: none;
  }
  .geosuggest__suggests-wrapper {
    position: absolute;
    top: 49px;
    left: 0;
    background-color: #3f3f3f;
  }
  .geosuggest__suggests-wrapper ul {
    padding: 0;
    margin: 0;
    list-style: none;
  }
  .geosuggest-item {
    color: #868fa0;
    font-size: 14px;
    padding: .5em .65em;
    cursor: pointer;
    border-bottom: 1px solid #3b3d4d;
  }
  .geosuggest__suggests--hidden {
    max-height: 0;
    overflow: hidden;
    border-width: 0;
  }
  .geosuggest-item--active {
    background: #267dc0;
    color: #fff;
  }
`

export default LocationSearch

```

**Comment by ro-ka** [comment] 2017-06-21 13:17
I think this is a duplicate of #251.

**Comment by Shooshte** [comment] 2017-06-22 11:36
@ro-ka 
Yes, seems like a duplicate, though I would not connect the two issues by myself.

So the preferred workaround is to call .blur() and then .focus() after the onSuggestSelect?
This seems hackish and unnecessary. Is there an event that updates the suggestion list instead?

Thanks for the help

**Comment by joanrodriguez** [comment] 2017-07-25 21:27
I have fixed your bug in this pull request: https://github.com/ubilabs/react-geosuggest/pull/340

**Comment by ro-ka** [comment] 2019-01-18 11:59
PR got merged, closing this.

**Closed by ro-ka** 2019-01-18 11:59 UTC
Labels: duplicate
