### ISSUE TITLE
Warning: Prop `aria-owns` did not match.

### ISSUE THREAD

**Issue by adamklepacz** [ubilabs/react-geosuggest#468] opened 2020-06-03 13:31 UTC
### Short description

I was trying to do use Geosuggest component within next.js app but I got this error:
```
Warning: Prop `aria-owns` did not match. Server: "geosuggest__list_251fcd4c58fb2" Client: "geosuggest__list_bad54fa98a27f
```

### Expected results

I expected that by will work without throwing an errors.

### Actual results

Instead of this, below error is thrown:

![localhost:3001 2020-06-03 15-21-11](https://user-images.githubusercontent.com/27632432/83642318-f6b26380-a5ae-11ea-9d31-ee94b6a59aa7.png)

### Additional Information

This is my component: 
![SearchInput jsx — newst-storefront-fe-repo 2020-06-03 15-21-02](https://user-images.githubusercontent.com/27632432/83642390-121d6e80-a5af-11ea-83c7-24e65a9fcfb5.png)

This is an error: 
![localhost:3001 2020-06-03 15-21-11](https://user-images.githubusercontent.com/27632432/83642421-19447c80-a5af-11ea-9c12-93315b4ab7de.png)

I think it is related to how next.js works, it sees probably two instances of my GEO suggest. 
Even why I pass prop ID="test" it creates two separate instances on server and client.

Any ideas how to fix it in Next.js app?

@ro-ka  anything on this?

**Comment by ro-ka** [comment] 2020-06-19 13:15
Duplicate of  #452.

**Closed by ro-ka** 2020-06-19 13:15 UTC
